name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  sketchy_design_lang:
    path: ../

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  flutter_test:
    sdk: flutter
